"""
SEO Score Calculator

Calculates an overall SEO score based on detected issues.
"""


def calculate_seo_score(issues):
    """
    Calculate an SEO score from a list of issues.

    Parameters:
        issues (list): List of issues generated by seo_evaluator.py

    Returns:
        dict: Score and grade.
    """

    # Start with a perfect score
    score = 100

    # Reduce score based on issue severity
    for issue in issues:

        severity = issue.get("severity")

        if severity == "High":
            score -= 15

        elif severity == "Medium":
            score -= 7

        elif severity == "Low":
            score -= 3

    # Prevent negative values
    score = max(score, 0)

    # Assign grade
    if score >= 90:
        grade = "A"

    elif score >= 80:
        grade = "B"

    elif score >= 70:
        grade = "C"

    elif score >= 60:
        grade = "D"

    else:
        grade = "F"

    return {

        "score": score,

        "grade": grade

    }